build.gradle
core/src/main/java/com/uber/m3/tally/ScopeBuilder.java
core/src/test/java/com/uber/m3/tally/ScopeImplTest.java
m3/src/main/java/com/uber/m3/tally/m3/M3Reporter.java

Making `ScopeBuilder` internal variables protected.
We don't need the `net.researchgate.release` plugin and associated attributes because our release process is to deploy to Maven Central instead of via tags.

Make ScopeBuilder variables protected

---

core/src/main/java/com/uber/m3/tally/Stopwatch.java
core/src/test/java/com/uber/m3/tally/TimerImplTest.java

Normally methods are lowercase in Java. I added a lowercase version of `stop` and marked the uppercase one as deprecated. This makes sure we don't break backwards compatibility.

Make Stopwatch.Stop() lowercase.

---

m3/src/main/java/com/uber/m3/tally/m3/M3Reporter.java

There's an (unhandled) exception when reporting histograms using the M3Reporter:
```
java.lang.UnsupportedOperationException
at com.uber.m3.util.ImmutableMap.put(ImmutableMap.java:129)
at com.uber.m3.tally.m3.M3Reporter.reportHistogramDurationSamples(M3Reporter.java:434)
at com.uber.m3.tally.HistogramImpl.report(HistogramImpl.java:136)
at com.uber.m3.tally.ScopeImpl.report(ScopeImpl.java:196)
at com.uber.m3.tally.ScopeImpl.reportLoopIteration(ScopeImpl.java:360)
at com.uber.m3.tally.ScopeImpl.access$000(ScopeImpl.java:35)
at com.uber.m3.tally.ScopeImpl$ReportLoop.run(ScopeImpl.java:369)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308)
at …
```

copy tags before modifing in M3Reporter

---

core/src/main/java/com/uber/m3/tally/ScopeImpl.java
core/src/test/java/com/uber/m3/tally/ScopeImplTest.java

Reporter is not required and everywhere where it's being used, it's surrounded with a null check; except in `ScopeImpl.close`...

Fix NullPointerException in ScopeImpl.close

---

m3/src/main/java/com/uber/m3/tally/m3/M3Reporter.java

`M3Reporter` mutates the base tags provided to it while reporting Value based histogram. This is going to fail if the base tags are wrapped under `ImmutableMap` and going to corrupt the tags around all the metrics if it is under mutable Map.
Duration based histogram takes care of this. Value based histogram probably missed it for some reason. 
This changeset fixes it.

Do not mutate base tags while reporting value based histograms

---

.travis.yml
build.gradle
core/src/main/java/com/uber/m3/tally/NoopScope.java
core/src/test/java/com/uber/m3/tally/NoopScopeTest.java
m3/src/main/java/com/uber/m3/tally/m3/M3Reporter.java

https://github.com/uber-java/tally/issues/34

Noop scope

---

core/src/main/java/com/uber/m3/tally/ScopeImpl.java

In our application the metric tags are dynamic, so we end up calling ScopeImpl#tagged api for the subscope, each time a metric in emitted. We have upto 10^5 metric series in one environment. The global lock is resulting in many threads in blocked state. 
Moving to concurrentHashMap, we atmost put a read-write lock on a particular bucket rather than whole object.

remove global lock for subscope computation

---

m3/src/main/java/com/uber/m3/tally/m3/M3Reporter.java
m3/src/main/java/com/uber/m3/tally/m3/thrift/TUdpClient.java
m3/src/main/java/com/uber/m3/tally/m3/thrift/TUdpTransport.java

This is putting severe pressure on our service currently (T5668949).
Primary factors for that are discrepancies between `M3Reporter.DEFAULT_MAX_PACKET_SIZE` and `TUdpTransport.MAX_BUFFER_SIZE` triggering allocations of 65kb buffer for the payload of 1.5kb (v0.4.1).
This change:
1.  Eliminates those unnecessary allocations altogether
2. Re-aligns `M3Reporter` buffer size along with `TUdpTransport` one tying it to max UDP data payload size

Fixing excessive memory allocations within M3Reporter flushing pipeline

---

build.gradle
m3/src/main/java/com/uber/m3/tally/m3/M3Reporter.java
m3/src/main/java/com/uber/m3/tally/m3/thrift/TUdpClient.java
m3/src/main/java/com/uber/m3/tally/m3/thrift/TUdpTransport.java
m3/src/test/java/com/uber/m3/tally/m3/M3ReporterTest.java
m3/src/test/java/com/uber/m3/tally/m3/MockM3Server.java
m3/src/test/java/com/uber/m3/tally/m3/MockM3Service.java
m3/src/test/java/com/uber/m3/tally/m3/thrift/TUdpClientTest.java

1. Cleaned up `TUdpClient` implementation and added tests
2. Refactored `M3Reporter` implementation
- Cleaned up/abstracted common ports
- Abolished unnecessary locking
- Made sure that flushing is guaranteed to happen at most `MAX_DELAY` ms
- Added proper shutdown short-circuiting
3. Fixed tests misusing `Phaser` (and flakily failing)

Refactored `M3Reporter` implementation

---

m3/src/main/java/com/uber/m3/tally/m3/M3Reporter.java
m3/src/main/java/com/uber/m3/tally/m3/thrift/TUdpTransport.java
m3/src/test/java/com/uber/m3/tally/m3/M3ReporterTest.java
m3/src/test/java/com/uber/m3/tally/m3/MockM3Server.java
m3/src/test/java/com/uber/m3/tally/m3/MockM3Service.java
m3/src/test/java/com/uber/m3/tally/m3/thrift/TUdpClientTest.java

Previously Thrift protocol overhead was factored using constant `19` which in reality is `21` right now and due to previous changes in the target buffer payload size M3 reporter started to hit that exception pretty consistently with metrics payload exceeding size of the buffer allocated obliterating our metrics.
1. Added proper size estimation: using the same client being used for actual payload serialization over the wire; 
2. Removed magic constant, added padding of 256 bytes for any future metadata being added
3. Added test overflowing single datagram buffer size with metrics' (size) small enough to hit future potential discrepancies between max UDP datagram packet size and `M3Reporter` configuration

Fixing improper payload size estimation

---

build.gradle
gradle.properties
m3/src/main/java/com/uber/m3/tally/m3/M3Reporter.java
m3/src/main/java/com/uber/m3/tally/m3/SizedMetric.java
m3/src/main/java/com/uber/m3/tally/m3/thrift/TUdpClient.java
m3/src/main/java/com/uber/m3/tally/m3/thrift/TUdpServer.java
m3/src/main/java/com/uber/m3/tally/m3/thrift/TUdpTransport.java
m3/src/test/java/com/uber/m3/tally/m3/M3ReporterTest.java
m3/src/test/java/com/uber/m3/tally/m3/MockM3Server.java
m3/src/test/java/com/uber/m3/tally/m3/MockM3Service.java

Fixing `M3Reporter.Processor` preparing it for multi-processor setup.
Previously even though `M3Reporter` had been setup to run 10 Processors, it never actually worked properly and by pure luck it wasn't actually corrupting its own state (due to those errors somewhat saving it from it): 
1. Flushing sequence didn't work: flush was only triggered within a single processor
2. Processors were sharing the same transport without ANY synchronization which might potentially end up in corrupted payload being sent over the wire
This change addresses all of those issues.
However, additional tests needs to be written along with current existing fixed.

Fix M3Reporter.Processor Flaky Tests

---

core/build.gradle
core/src/jmh/java/com/uber/m3/tally/ScopeImplBenchmark.java
core/src/main/java/com/uber/m3/tally/BucketPairImpl.java
core/src/main/java/com/uber/m3/tally/CounterImpl.java
core/src/main/java/com/uber/m3/tally/GaugeImpl.java
core/src/main/java/com/uber/m3/tally/HistogramImpl.java
core/src/main/java/com/uber/m3/tally/MetricBase.java
core/src/main/java/com/uber/m3/tally/Reportable.java
core/src/main/java/com/uber/m3/tally/ScopeImpl.java
core/src/test/java/com/uber/m3/tally/CounterImplTest.java
core/src/test/java/com/uber/m3/tally/GaugeImplTest.java
core/src/test/java/com/uber/m3/tally/HistogramImplTest.java

This is a follow-up for #73 to further reduce CPU churn by avoiding traversing empty arrays, and instead lazily subscribing individual buckets for reporting into enclosing scope.
```
Benchmark                                    Mode  Cnt    Score   Error   Units
ScopeImplBenchmark.scopeReportingBenchmark  thrpt   10  465.752 ± 7.296  ops/ms
Benchmark                                    Mode  Cnt    Score    Error   Units
ScopeImplBenchmark.scopeReportingBenchmark  thrpt   10  434.375 ± 26.114  ops/ms
Benchmark                                    Mode  Cnt     Score    Error   Units
ScopeImplBenchmark.scopeReportingBenchmark  thrpt   10  1929.097 ± 23.396  ops/ms
Benchmark                                    Mode  Cnt     Score    Error   Units
ScopeImplBenchmark.scopeReportingBenchmark …
```

Refactored Histogram impl to avoid CPU churn

---

core/src/main/java/com/uber/m3/tally/AbstractBuckets.java
core/src/main/java/com/uber/m3/tally/BucketPairImpl.java
core/src/main/java/com/uber/m3/tally/Buckets.java
core/src/main/java/com/uber/m3/tally/DurationBuckets.java
core/src/main/java/com/uber/m3/tally/HistogramImpl.java
core/src/main/java/com/uber/m3/tally/ImmutableBuckets.java
core/src/main/java/com/uber/m3/tally/ScopeImpl.java
core/src/main/java/com/uber/m3/tally/ValueBuckets.java
core/src/main/java/com/uber/m3/util/ImmutableList.java
core/src/test/java/com/uber/m3/tally/DurationBucketsTest.java
core/src/test/java/com/uber/m3/tally/HistogramImplTest.java
core/src/test/java/com/uber/m3/tally/ScopeImplTest.java
core/src/test/java/com/uber/m3/tally/TestStatsReporter.java
core/src/test/java/com/uber/m3/tally/ValueBucketsTest.java
m3/src/main/java/com/uber/m3/tally/m3/M3Reporter.java
m3/src/test/java/com/uber/m3/tally/m3/M3ReporterTest.java

Subject;
NOTE: There's a breaking change: `DurationBuckets` and `LatencyBuckets` will no longer be modifiable.
Introduced `ImmutableBuckets` interface to eventually replaced `Buckets`;
Rebased `HistogramImpl`, `M3Reporter` onto `ImmutableBuckets`

Refactored M3 reporting to remove any unnecessary allocations

---

m3/src/main/java/com/uber/m3/tally/m3/M3Reporter.java
m3/src/test/java/com/uber/m3/tally/m3/M3ReporterTest.java

Currently crashed `Processor` would eventually lead to the `M3Reporter` queue to overflow and block on attempts to add metrics to it stalling the calling application.
This change makes `M3Reporter` more resilient by adding heartbeat sequence checking the state of the processors and rebooting the failings ones. 
It also makes sure that addition to the queue never jams the application itself.
More details could be found in T6503863.

Fixing M3Reporter to reboot Processors upon failure

---

m3/src/main/java/com/uber/m3/tally/m3/thrift/TUdpClient.java
m3/src/main/java/com/uber/m3/tally/m3/thrift/TUdpServer.java
m3/src/main/java/com/uber/m3/tally/m3/thrift/TUdpTransport.java
m3/src/test/java/com/uber/m3/tally/m3/thrift/TUdpClientTest.java

Add an `open` flag to `TUdpTransport` to avoid querying `DatagramSocket::isOpen` on the hot-path (incurs lock acquiring)

Add an `open` flag to `TUdpTransport`

---

README.md
prometheus/README.md
prometheus/src/main/java/com/uber/m3/tally/experimental/prometheus/PrometheusReporter.java
prometheus/src/main/java/com/uber/m3/tally/experimental/prometheus/TimerType.java
prometheus/src/test/java/com/uber/m3/tally/experimental/prometheus/PrometheusReporterTest.java

As discussed with @alexeykudinkin and @SokolAndrey, we're not quite ready to have the prom reporter actively used by folks. It's already released (hard to undo), but we can at least give users a heads up for the time being. I figure we can probably remove these once we've addressed perf concerns and maybe done some baking of the lib within Uber.

Add WIP warnings around prom reporter

---

build.gradle
core/src/main/java/com/uber/m3/tally/NoopScope.java
core/src/main/java/com/uber/m3/tally/Scope.java
core/src/main/java/com/uber/m3/tally/ScopeImpl.java

A user pointed out that there's no way currently to use the default buckets (specified via `null`) in a project that
uses https://github.com/uber/NullAway. That library assumes that anything unannotated is @NotNull, which is aggressive but probably the right move. To remedy this, I've just gone and explicitly marked `histogram` as nullable.
We can annotate further as we get time/touch the code naturally.
A note r.e. the findbugs dependency--this seems like a fairly standard source for the annotation, but if there's a better one let me know.

Add @Nullable annotation to histogram to make it work with the NullAway linter

---

core/benchmark-tests.txt
core/build.gradle
core/src/jmh/java/com/uber/m3/tally/AbstractReporterBenchmark.java
core/src/main/java/com/uber/m3/tally/ScopeImpl.java
core/src/main/java/com/uber/m3/util/ListSet.java
m3/benchmark-tests.txt
m3/build.gradle
m3/src/jmh/java/com/uber/m3/tally/m3/M3ReporterBenchmark.java
m3/src/main/java/com/uber/m3/tally/m3/M3Reporter.java
prometheus/build.gradle
prometheus/src/jmh/java/com/uber/m3/tally/experimental/prometheus/PrometheusReporterBenchmark.java
statsd/build.gradle
statsd/src/jmh/java/com/uber/m3/tally/statsd/StatsdReporterBenchmark.java

Current implementation of Tally relies on `BlockingLinkedQueue` making each reporting of the metric to acquire lock while adding the metrics to the processing queue, contending w/ the `M3Processor` trying to read from the same queue.
Since there are hardly any good reasons for us to rely on the blocking queue, i've refactored `M3Reporter` to rely on non-blocking lock-free queue implementation (`ConcurrentLinkedQueue`).
However to preserve previous semantic of `M3Reporter.Processor` being parked in case there are no currently metrics enqueued for processing, as well as it being notified whenever there are new metrics in the queue, `Condition` is being used to notify and un-park processors.

Optimizing M3 Reporter

---

core/build.gradle
core/jmhFixtures.gradle
core/src/jmh/java/com/uber/m3/tally/ScopeImplConcurrent.java
core/src/main/java/com/uber/m3/tally/ScopeImpl.java

We have found that for java applications running on big machines (>8 cores) we start to see sudden spikes in latency. For instance a 32 core service gets a 100 ms spike which affect our p99.9.
By calling .get() before computeIfAbsent() we are able to reduce the impact of this (we can't completely remove it because we could still be allocating new keys).
We added a benchmark to demonstrate this. The 32 thread results are as follows:
**Before the fix**
**After the fix**

Check scope existence lock free first

---

core/src/main/java/com/uber/m3/tally/NullStatsReporter.java
core/src/main/java/com/uber/m3/tally/ScopeImpl.java
core/src/main/java/com/uber/m3/tally/TestScope.java
core/src/main/java/com/uber/m3/util/ImmutableMap.java
core/src/test/java/com/uber/m3/tally/NullStatsReporterTest.java
core/src/test/java/com/uber/m3/tally/ScopeImplTest.java
core/src/test/java/com/uber/m3/tally/TestScopeTest.java

This commit plucks select changes from uber-java/tally#69 and uber-java/tally#43 to bring [uber-java/tally](https://github.com/uber-java/tally) on par with [uber-go/tally](https://github.com/uber-go/tally).
It adds a `TestScope` class which allows users of the library to get a `Snapshot` of all the metrics emitted by the scope. Users can then assert if certain metrics were created on the scope.
In order to implement this a `NullStatsReporter` was added and a `TestScope` interface was added that exposes
the `snapshot` method. The `snapshot` method was also changed to ensure that a subscope's tags were included
when creating the snapshot. Also the `putAll` method of the `ImmutableMap` was made null safe.  Also `ScopeKey`
was made null safe.
`TestScopeTest` shows how the `TestScope` can be …

Add TestScope

---

.github/workflows/gradle.yml
build.gradle
core/src/test/java/com/uber/m3/tally/BucketPairImplTest.java
gradle/wrapper/gradle-wrapper.properties

Just some hygiene--we're a full 3 major versions behind at this point. 
Notes: cant go to 7.x just yet; we have some deprecated things to fix up. Doing this step wise (will go to 7.x in a subsequent PR, probably).

Upgrade gradle version to 6.9.2

---

core/src/main/java/com/uber/m3/tally/ScopeImpl.java
core/src/test/java/com/uber/m3/tally/TestScopeTest.java

https://github.com/uber-java/tally/pull/120 has a bug where the `Snapshot` only includes the subscopes and not the metrics on the current scope. This fixes the `snapshot` method to include metrics on the current scope as well.

Fix Snapshots creation
